syntax keyword luaFunc
      \ self
      \ __index
      \ __newindex
      \ __mode
      \ __call
      \ __metatable
      \ __tostring
      \ __len
      \ __pairs
      \ __ipairs
      \ __gc
      \ __unm
      \ __add
      \ __sub
      \ __mul
      \ __div
      \ __mod
      \ __div
      \ __idiv
      \ __mod
      \ __pow
      \ __concat
      \ __eq
      \ __lt
      \ __le
